spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        auto_quote_keyword: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:tes;MODE=MySQL;NON_KEYWORDS=GROUP,photo
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true