spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        auto_quote_keyword: true
    defer-datasource-initialization: true

  datasource:
    url: "jdbc:mysql://localhost/Memory"
    username: "root"
    password: "Cokothon1234!" # MySQL ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver